DROP DATABASE IF EXISTS LAF;
CREATE DATABASE LAF;

USE LAF;

CREATE TABLE USER (
    User_id INT AUTO_INCREMENT,
    Inserted_at TIMESTAMP NOT NULL,
    Email VARCHAR(50) UNIQUE NOT NULL,
    Password VARCHAR(50) UNIQUE NOT NULL,
    
    PRIMARY KEY (User_id)
);

CREATE TABLE ITEM (
    Item_id INT AUTO_INCREMENT,
    Inserted_at TIMESTAMP NOT NULL,
    Location VARCHAR(50) NOT NULL,
    Description VARCHAR(250) NOT NULL,
    Title VARCHAR(50) NOT NULL, 
    Type VARCHAR(20) NOT NULL,
    Status VARCHAR(20) NOT NULL,
	User_id INT NOT NULL,
    Date DATE NOT NULL,
    Img BLOB NOT NULL,

    PRIMARY KEY (Item_id),
    FOREIGN KEY (User_id) REFERENCES USER (User_id)
);
